"""Generates fuzzing harnesses for different vulnerability types."""

import os
from typing import List, Optional
from pathlib import Path


class HarnessGenerator:
    """Generates PHP fuzzing harnesses for vulnerability validation."""

    def __init__(self, wordpress_path: str = "/var/www/html", plugins_path: str = None):
        """
        Initialize harness generator.

        Args:
            wordpress_path: Path to WordPress installation
            plugins_path: Path to plugins directory
        """
        self.wordpress_path = wordpress_path
        self.plugins_path = plugins_path or os.path.join(wordpress_path, "wp-content/plugins")

    def generate_harness(
        self,
        vulnerability_type: str,
        plugin_slug: str,
        matched_files: List[str],
        matched_code: Optional[List[str]] = None,
        signature_id: Optional[str] = None,
    ) -> str:
        """
        Generate fuzzing harness for a vulnerability.

        Args:
            vulnerability_type: Type of vulnerability (CSRF, SQLi, XSS, etc.)
            plugin_slug: Plugin slug
            matched_files: Files containing vulnerable code
            matched_code: Optional code snippets
            signature_id: Optional CVE/signature ID

        Returns:
            str: Generated PHP harness code
        """
        # Normalize vulnerability type
        vuln_type = vulnerability_type.lower().replace(' ', '_').replace('-', '_')

        # Map to handler
        type_mapping = {
            'sql_injection': self._generate_sqli_harness,
            'sqli': self._generate_sqli_harness,
            'cross_site_scripting': self._generate_xss_harness,
            'xss': self._generate_xss_harness,
            'xss_stored': self._generate_xss_harness,
            'xss_reflected': self._generate_xss_harness,
            'csrf': self._generate_csrf_harness,
            'path_traversal': self._generate_path_traversal_harness,
            'directory_traversal': self._generate_path_traversal_harness,
            'lfi': self._generate_path_traversal_harness,
            'authentication_bypass': self._generate_auth_bypass_harness,
            'authorization_bypass': self._generate_auth_bypass_harness,
            'auth_bypass': self._generate_auth_bypass_harness,
            'file_upload': self._generate_file_upload_harness,
            'arbitrary_file_upload': self._generate_file_upload_harness,
        }

        generator_func = type_mapping.get(vuln_type, self._generate_generic_harness)

        return generator_func(
            plugin_slug=plugin_slug,
            matched_files=matched_files,
            matched_code=matched_code,
            signature_id=signature_id
        )

    def _generate_sqli_harness(
        self,
        plugin_slug: str,
        matched_files: List[str],
        matched_code: Optional[List[str]] = None,
        signature_id: Optional[str] = None,
    ) -> str:
        """Generate SQL injection fuzzing harness."""
        target_file = matched_files[0] if matched_files else "index.php"

        return f'''<?php
/**
 * SQL Injection Fuzzing Harness
 *
 * Plugin: {plugin_slug}
 * Signature: {signature_id or "N/A"}
 * Target: {target_file}
 *
 * Generated by Phase 3 Fuzzing Validator
 */

// Suppress output to detect crashes cleanly
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Read fuzzing input
if (!isset($argv[1])) {{
    die("Usage: php harness.php <input_file>\\n");
}}

$fuzz_input = file_get_contents($argv[1]);
if ($fuzz_input === false) {{
    die("Failed to read input file\\n");
}}

// Load WordPress
define('ABSPATH', '{self.wordpress_path}/');
require_once ABSPATH . 'wp-load.php';

// Inject fuzz input into vulnerable parameters
// Try multiple parameter positions
$_GET['id'] = $fuzz_input;
$_POST['id'] = $fuzz_input;
$_REQUEST['id'] = $fuzz_input;

$_GET['user_id'] = $fuzz_input;
$_POST['user_id'] = $fuzz_input;

$_GET['post_id'] = $fuzz_input;
$_POST['post_id'] = $fuzz_input;

// Set up WordPress environment
$_SERVER['REQUEST_METHOD'] = 'POST';
$_SERVER['HTTP_HOST'] = 'localhost';
$_SERVER['REQUEST_URI'] = '/wp-admin/admin-ajax.php';

// Hook into WordPress database errors
global $wpdb;
$wpdb->show_errors();
$original_suppress_errors = $wpdb->suppress_errors;
$wpdb->suppress_errors(false);

// Capture database errors
$db_error_detected = false;
add_filter('pre_query', function($query) use (&$db_error_detected) {{
    // Log the query for analysis
    error_log("FUZZ_QUERY: " . $query);
    return $query;
}});

// Start output buffering to catch errors
ob_start();

try {{
    // Include the vulnerable plugin file
    $plugin_file = '{self.plugins_path}/{plugin_slug}/{target_file}';
    if (file_exists($plugin_file)) {{
        include $plugin_file;
    }}

    // Try to trigger common vulnerable patterns
    if (function_exists('wp_ajax_nopriv_')) {{
        do_action('wp_ajax_nopriv_custom_action');
    }}

}} catch (Exception $e) {{
    echo "CRASH: " . $e->getMessage() . "\\n";
    exit(1);
}} catch (Error $e) {{
    echo "FATAL: " . $e->getMessage() . "\\n";
    exit(1);
}}

$output = ob_get_clean();

// Check for SQL errors in output
$sql_error_patterns = [
    '/SQL syntax/i',
    '/mysql_fetch/i',
    '/mysqli_fetch/i',
    '/You have an error in your SQL/i',
    '/Warning.*mysql/i',
    '/Duplicate entry/i',
    '/Unknown column/i',
    '/Table.*doesn\'t exist/i',
    '/wpdb->prepare/i',
];

foreach ($sql_error_patterns as $pattern) {{
    if (preg_match($pattern, $output)) {{
        echo "SQL_ERROR_DETECTED\\n";
        echo "Pattern: $pattern\\n";
        echo "Output: " . substr($output, 0, 500) . "\\n";
        exit(1);
    }}
}}

// Check for database errors
if ($wpdb->last_error) {{
    echo "SQL_ERROR_DETECTED\\n";
    echo "Error: " . $wpdb->last_error . "\\n";
    exit(1);
}}

// No crash detected
exit(0);
?>
'''

    def _generate_xss_harness(
        self,
        plugin_slug: str,
        matched_files: List[str],
        matched_code: Optional[List[str]] = None,
        signature_id: Optional[str] = None,
    ) -> str:
        """Generate XSS fuzzing harness."""
        target_file = matched_files[0] if matched_files else "index.php"

        return f'''<?php
/**
 * XSS Fuzzing Harness
 *
 * Plugin: {plugin_slug}
 * Signature: {signature_id or "N/A"}
 * Target: {target_file}
 */

error_reporting(E_ALL);
ini_set('display_errors', 0);

// Read fuzzing input
$fuzz_input = file_get_contents($argv[1]);

// Load WordPress
define('ABSPATH', '{self.wordpress_path}/');
require_once ABSPATH . 'wp-load.php';

// Inject fuzz input into vulnerable parameters
$_GET['search'] = $fuzz_input;
$_POST['comment'] = $fuzz_input;
$_GET['q'] = $fuzz_input;
$_POST['message'] = $fuzz_input;
$_GET['name'] = $fuzz_input;

ob_start();

try {{
    $plugin_file = '{self.plugins_path}/{plugin_slug}/{target_file}';
    if (file_exists($plugin_file)) {{
        include $plugin_file;
    }}
}} catch (Exception $e) {{
    echo "CRASH: " . $e->getMessage() . "\\n";
    exit(1);
}}

$output = ob_get_clean();

// Detect reflected XSS - check if input is reflected without escaping
if (strpos($output, $fuzz_input) !== false) {{
    // Check if it's NOT escaped
    $escaped_versions = [
        htmlspecialchars($fuzz_input, ENT_QUOTES, 'UTF-8'),
        htmlentities($fuzz_input, ENT_QUOTES, 'UTF-8'),
        esc_html($fuzz_input),
        esc_attr($fuzz_input),
    ];

    $is_escaped = false;
    foreach ($escaped_versions as $escaped) {{
        if (strpos($output, $escaped) !== false) {{
            $is_escaped = true;
            break;
        }}
    }}

    if (!$is_escaped) {{
        echo "XSS_DETECTED: Input reflected without escaping\\n";
        echo "Input: $fuzz_input\\n";
        exit(1);
    }}
}}

// Detect DOM-based XSS patterns
$xss_patterns = [
    '/<script[^>]*>.*?' . preg_quote($fuzz_input, '/') . '/i',
    '/onerror\\s*=\\s*["\']?' . preg_quote($fuzz_input, '/') . '/i',
    '/onload\\s*=\\s*["\']?' . preg_quote($fuzz_input, '/') . '/i',
    '/javascript:.*?' . preg_quote($fuzz_input, '/') . '/i',
];

foreach ($xss_patterns as $pattern) {{
    if (preg_match($pattern, $output)) {{
        echo "XSS_DETECTED: Dangerous pattern found\\n";
        exit(1);
    }}
}}

exit(0);
?>
'''

    def _generate_csrf_harness(
        self,
        plugin_slug: str,
        matched_files: List[str],
        matched_code: Optional[List[str]] = None,
        signature_id: Optional[str] = None,
    ) -> str:
        """Generate CSRF fuzzing harness."""
        target_file = matched_files[0] if matched_files else "index.php"

        return f'''<?php
/**
 * CSRF Fuzzing Harness
 *
 * Plugin: {plugin_slug}
 * Signature: {signature_id or "N/A"}
 * Target: {target_file}
 */

error_reporting(E_ALL);
ini_set('display_errors', 0);

// Read fuzzing input (e.g., "action=delete_user&user_id=1")
$fuzz_input = file_get_contents($argv[1]);

// Load WordPress
define('ABSPATH', '{self.wordpress_path}/');
require_once ABSPATH . 'wp-load.php';

// Parse input into parameters
parse_str($fuzz_input, $params);
$_POST = array_merge($_POST, $params);
$_GET = array_merge($_GET, $params);
$_REQUEST = array_merge($_REQUEST, $params);

// CRITICAL: Remove nonce to test CSRF
unset($_POST['_wpnonce']);
unset($_GET['_wpnonce']);
unset($_REQUEST['_wpnonce']);
unset($_POST['nonce']);
unset($_GET['nonce']);

// Simulate unauthenticated request
wp_set_current_user(0);

$_SERVER['REQUEST_METHOD'] = 'POST';

// Track if privileged action was performed
$privileged_action_performed = false;

// Hook into actions that shouldn't work without nonce
add_action('wp_ajax_nopriv_*', function() use (&$privileged_action_performed) {{
    $privileged_action_performed = true;
}}, 1);

// Hook into database writes
global $wpdb;
$original_query = [$wpdb, 'query'];
$write_operations = ['INSERT', 'UPDATE', 'DELETE', 'CREATE', 'DROP', 'ALTER'];

add_filter('query', function($query) use (&$privileged_action_performed, $write_operations) {{
    foreach ($write_operations as $op) {{
        if (stripos($query, $op) === 0) {{
            $privileged_action_performed = true;
            error_log("PRIVILEGED_WRITE: $query");
        }}
    }}
    return $query;
}});

ob_start();

try {{
    $plugin_file = '{self.plugins_path}/{plugin_slug}/{target_file}';
    if (file_exists($plugin_file)) {{
        include $plugin_file;
    }}

    // Try to trigger AJAX actions
    if (isset($params['action'])) {{
        do_action('wp_ajax_nopriv_' . $params['action']);
        do_action('wp_ajax_' . $params['action']);
    }}

}} catch (Exception $e) {{
    echo "CRASH: " . $e->getMessage() . "\\n";
    exit(1);
}}

$output = ob_get_clean();

// Check if privileged action was performed without nonce
if ($privileged_action_performed) {{
    echo "CSRF_DETECTED: Privileged action performed without nonce verification\\n";
    exit(1);
}}

exit(0);
?>
'''

    def _generate_path_traversal_harness(
        self,
        plugin_slug: str,
        matched_files: List[str],
        matched_code: Optional[List[str]] = None,
        signature_id: Optional[str] = None,
    ) -> str:
        """Generate path traversal fuzzing harness."""
        target_file = matched_files[0] if matched_files else "index.php"

        return f'''<?php
/**
 * Path Traversal Fuzzing Harness
 *
 * Plugin: {plugin_slug}
 * Signature: {signature_id or "N/A"}
 * Target: {target_file}
 */

error_reporting(E_ALL);
ini_set('display_errors', 0);

// Read fuzzing input (e.g., "../../wp-config.php")
$fuzz_input = file_get_contents($argv[1]);

// Load WordPress
define('ABSPATH', '{self.wordpress_path}/');
require_once ABSPATH . 'wp-load.php';

// Inject into file-related parameters
$_GET['file'] = $fuzz_input;
$_POST['file'] = $fuzz_input;
$_GET['path'] = $fuzz_input;
$_POST['path'] = $fuzz_input;
$_GET['download'] = $fuzz_input;

// Track accessed files
$accessed_files = [];

// Wrap file operations to detect traversal
$GLOBALS['fuzz_accessed_files'] = [];

// Override file_get_contents
function fuzz_file_get_contents($filename) {{
    $GLOBALS['fuzz_accessed_files'][] = $filename;
    return @file_get_contents($filename);
}}

// Override fopen
function fuzz_fopen($filename, $mode) {{
    $GLOBALS['fuzz_accessed_files'][] = $filename;
    return @fopen($filename, $mode);
}}

ob_start();

try {{
    $plugin_file = '{self.plugins_path}/{plugin_slug}/{target_file}';
    if (file_exists($plugin_file)) {{
        include $plugin_file;
    }}
}} catch (Exception $e) {{
    echo "CRASH: " . $e->getMessage() . "\\n";
    exit(1);
}}

$output = ob_get_clean();

// Check for path traversal indicators
$sensitive_files = [
    'wp-config.php',
    '/etc/passwd',
    '/etc/shadow',
    '\\\\windows\\\\system32',
];

foreach ($GLOBALS['fuzz_accessed_files'] as $file) {{
    foreach ($sensitive_files as $sensitive) {{
        if (stripos($file, $sensitive) !== false) {{
            echo "PATH_TRAVERSAL_DETECTED: Accessed $file\\n";
            exit(1);
        }}
    }}

    // Check for directory traversal patterns
    if (strpos($file, '../') !== false || strpos($file, '..\\\\') !== false) {{
        echo "PATH_TRAVERSAL_DETECTED: Traversal pattern in $file\\n";
        exit(1);
    }}
}}

// Check output for file contents
if (strpos($output, 'DB_NAME') !== false ||
    strpos($output, 'DB_PASSWORD') !== false ||
    strpos($output, 'root:') !== false) {{
    echo "PATH_TRAVERSAL_DETECTED: Sensitive data in output\\n";
    exit(1);
}}

exit(0);
?>
'''

    def _generate_auth_bypass_harness(
        self,
        plugin_slug: str,
        matched_files: List[str],
        matched_code: Optional[List[str]] = None,
        signature_id: Optional[str] = None,
    ) -> str:
        """Generate authentication bypass fuzzing harness."""
        target_file = matched_files[0] if matched_files else "index.php"

        return f'''<?php
/**
 * Authentication Bypass Fuzzing Harness
 *
 * Plugin: {plugin_slug}
 * Signature: {signature_id or "N/A"}
 * Target: {target_file}
 */

error_reporting(E_ALL);
ini_set('display_errors', 0);

// Read fuzzing input
$fuzz_input = file_get_contents($argv[1]);

// Load WordPress
define('ABSPATH', '{self.wordpress_path}/');
require_once ABSPATH . 'wp-load.php';

// Parse input
parse_str($fuzz_input, $params);
$_GET = array_merge($_GET, $params);
$_POST = array_merge($_POST, $params);

// Start as unauthenticated user
wp_set_current_user(0);
$was_authenticated_before = is_user_logged_in();

ob_start();

try {{
    $plugin_file = '{self.plugins_path}/{plugin_slug}/{target_file}';
    if (file_exists($plugin_file)) {{
        include $plugin_file;
    }}
}} catch (Exception $e) {{
    echo "CRASH: " . $e->getMessage() . "\\n";
    exit(1);
}}

$output = ob_get_clean();

// Check if we're now authenticated
$is_authenticated_after = is_user_logged_in();
$current_user = wp_get_current_user();

if (!$was_authenticated_before && $is_authenticated_after) {{
    echo "AUTH_BYPASS_DETECTED: Became authenticated without credentials\\n";
    echo "User: " . $current_user->user_login . "\\n";
    exit(1);
}}

// Check for admin-only content in output
$admin_indicators = [
    'wp-admin',
    'dashboard',
    'administrator',
];

foreach ($admin_indicators as $indicator) {{
    if (stripos($output, $indicator) !== false) {{
        echo "AUTH_BYPASS_DETECTED: Admin content accessible\\n";
        exit(1);
    }}
}}

exit(0);
?>
'''

    def _generate_file_upload_harness(
        self,
        plugin_slug: str,
        matched_files: List[str],
        matched_code: Optional[List[str]] = None,
        signature_id: Optional[str] = None,
    ) -> str:
        """Generate file upload fuzzing harness."""
        target_file = matched_files[0] if matched_files else "index.php"

        return f'''<?php
/**
 * File Upload Fuzzing Harness
 *
 * Plugin: {plugin_slug}
 * Signature: {signature_id or "N/A"}
 * Target: {target_file}
 */

error_reporting(E_ALL);
ini_set('display_errors', 0);

// Read fuzzing input (filename)
$fuzz_input = file_get_contents($argv[1]);

// Load WordPress
define('ABSPATH', '{self.wordpress_path}/');
require_once ABSPATH . 'wp-load.php';

// Simulate file upload
$upload_dir = wp_upload_dir();
$temp_file = tempnam(sys_get_temp_dir(), 'fuzz');
file_put_contents($temp_file, '<?php echo "PWNED"; ?>');

$_FILES['file'] = [
    'name' => $fuzz_input,
    'type' => 'application/octet-stream',
    'tmp_name' => $temp_file,
    'error' => 0,
    'size' => filesize($temp_file),
];

$uploaded_files = [];

// Hook into file uploads
add_filter('wp_handle_upload', function($file) use (&$uploaded_files) {{
    $uploaded_files[] = $file;
    return $file;
}});

ob_start();

try {{
    $plugin_file = '{self.plugins_path}/{plugin_slug}/{target_file}';
    if (file_exists($plugin_file)) {{
        include $plugin_file;
    }}
}} catch (Exception $e) {{
    echo "CRASH: " . $e->getMessage() . "\\n";
    exit(1);
}}

$output = ob_get_clean();

// Check if dangerous file was uploaded
$dangerous_extensions = ['.php', '.php5', '.phtml', '.phar'];

foreach ($uploaded_files as $file) {{
    $filename = $file['file'] ?? '';
    foreach ($dangerous_extensions as $ext) {{
        if (stripos($filename, $ext) !== false) {{
            echo "FILE_UPLOAD_DETECTED: Dangerous file uploaded: $filename\\n";
            @unlink($filename);
            exit(1);
        }}
    }}
}}

// Cleanup
@unlink($temp_file);

exit(0);
?>
'''

    def _generate_generic_harness(
        self,
        plugin_slug: str,
        matched_files: List[str],
        matched_code: Optional[List[str]] = None,
        signature_id: Optional[str] = None,
    ) -> str:
        """Generate generic fuzzing harness."""
        target_file = matched_files[0] if matched_files else "index.php"

        return f'''<?php
/**
 * Generic Fuzzing Harness
 *
 * Plugin: {plugin_slug}
 * Signature: {signature_id or "N/A"}
 * Target: {target_file}
 */

error_reporting(E_ALL);
ini_set('display_errors', 0);

// Read fuzzing input
$fuzz_input = file_get_contents($argv[1]);

// Load WordPress
define('ABSPATH', '{self.wordpress_path}/');
require_once ABSPATH . 'wp-load.php';

// Inject input into various parameters
$_GET['param'] = $fuzz_input;
$_POST['param'] = $fuzz_input;

ob_start();

try {{
    $plugin_file = '{self.plugins_path}/{plugin_slug}/{target_file}';
    if (file_exists($plugin_file)) {{
        include $plugin_file;
    }}
}} catch (Exception $e) {{
    echo "CRASH: " . $e->getMessage() . "\\n";
    exit(1);
}}

$output = ob_get_clean();

// Generic crash detection
if (stripos($output, 'fatal') !== false ||
    stripos($output, 'warning') !== false ||
    stripos($output, 'error') !== false) {{
    echo "CRASH_DETECTED\\n";
    exit(1);
}}

exit(0);
?>
'''

    def save_harness(self, harness_code: str, output_path: str) -> str:
        """
        Save harness to file.

        Args:
            harness_code: Generated PHP code
            output_path: Path to save harness

        Returns:
            str: Path to saved harness
        """
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        with open(output_path, 'w') as f:
            f.write(harness_code)

        # Make executable
        os.chmod(output_path, 0o755)

        return output_path
